baseurl = "https://advancetechmedia.org/"
languageCode = "en-US"
title = "Advance Tech Podcast"
theme = "castanet"
googleAnalytics = "UA-98351650-1"
disqusShortname = "advtechpodcast"
themesdir = "themes"



[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier

[[Menu.Main]]
    name = "Events"
    identifier = "events"
    url = "events"

[[Menu.Main]]
    name = "Guests"
    identifier = "guest"
    url = "guest"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

[[Menu.Main]]
   name = "Sponsor"
   identifier = "sponsor"
   url = "sponsor"

[[Menu.Main]]
    name = "Community"
    identifier = "community"
    url = "community"

#[[Menu.Main]]
#    name = "Syndicate"
#    identifier = "syndicate"
#    url = "syndicate"

[params]
site_theme = "blue"
site_layout = "row"
enable_jumbo = "true"
custom_css = ["css/custom.css"]
#truncate = "100"
about_logo = "/img/Advancetechmedia avatar.png"
media_prefix = "https://advancetechmedia.org/"

copyright_notice = "Copyright 2017 - 2020 [Advance Tech Media](https://.advancetechmedia.org)"
itunes_subscribe = "https://itunes.apple.com/ca/podcast/advance-tech-podcast/id1278222771"
android_subscribe = "https://www.subscribeonandroid.com/advancetechmedia.org/episode/index.xml"
google_play_subscribe = "https://play.google.com/music/listen?u=0#/ps/Ixpkgrijhidwwxqyz4qwfh4azhm"
stitcher_subscribe = "https://www.stitcher.com/s?fid=356388&refid=stpr"
spotify_subscribe = "https://open.spotify.com/show/4W4Lptk0ENfh7Wc1LKL3Zu"
pocketcasts_subscribe = "https://play.pocketcasts.com/web#/podcasts/show/8e189720-0f3b-0135-ecbb-4114446340cb"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "<p>The Advance Tech Podcast provides a spotlight for innovative and disruptive initiatives and features guests building the technology of tomorrow. Hosted by Alexandra Moxin and Adam Dymitruk.</p><p>We connect you to founders, developers and leaders from around the globe who give our audience insight into what it takes to massively scale from great idea to leading industry maker.</p><p>Subscribe from our homepage and check out our [commercial site](https://www.advancetechmedia.com/)"
  [params.feed]
    feed_copyright = "Copyright 2017 - 2019 Advance Tech Media" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "The voice of innovation and the tech of tomorrow." #no markdown or HTML
    itunes_author = "Alexandra Moxin" #no markdown or HTML
    itunes_summary = "The Advance Tech Podcast brings you the latest in bleeding edge technology and features guests building the technology of tomorrow. We connect you to founders, developers and influencers from around the globe who give our audience insight into what it takes to massively scale from great idea to leading industry maker. Hosted by Alexandra Moxin and Adam Dymitruk." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Advance Tech Media"
    itunes_owner_email = "alexandra.moxin@advancetechmedia.org" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "http://advancetechmedia.org/img/advancetechmediaavataritunes.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Tech News"
    itunes_second_sub_category = "Software How-To"
    itunes_third_sub_category = "Podcasting"

  [params.social]
    github = "advancetechmedia"
    #gitlab = "mattstratton"
    twitter = "AdvTechPodcast"
    linkedin = "/company/advance-tech-media/"
    #facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    facebook = "advancetechmedia"
    #twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    #googleplus = "ArrestedDevOps"
    #pinterest = "nozzleio"
    instagram = "advance_tech_media"
    youtube = "channel/UCo0YHhPVPBienDjnvqDrh1g"


  [params.authors]
    [params.authors.Adam]
      name	= "Adam Dymitruk"
      thumbnail = "img/host/adam-2016-small-square.png"
      bio = "<p>CEO and Founder of Adaptech Group, and Co-host of the Advance Tech Podcast, Adam is a pioneer in the event sourcing space. He founded the Event Modelling approach for designing and building information systems and is a core contributor to one of the earliest event sourcing projects in 2007 to 2008. He inspires organisations to excel in modern software development, a culture of learning and modern approaches to software architecture.</p>"
      [params.authors.Adam.social]
        github = "adymitruk"
        twitter = "adymitruk"
        linkedin = "eventsourcing"
        facebook = "adymitruk"
        homepage = "https://www.adaptechgroup.com"
        #pinterest = "mattstratton"
        instagram = "adamdymitruk"
        youtube = "adaptech"
    [params.authors.1Alex]
      name = "Alexandra Moxin"
      thumbnail = "img/host/Alex1.jpg"
      bio = "<p>CEO and Founder of Advance Tech Media and Host of the Advance Tech Podcast Alexandra interviews founders, developers and leaders from around the globe shining a light on what it takes to massively scale from great idea to leading industry maker. She speaks at conferences and for private groups in Canada and internationally on Artificial Intelligence/Machine Learning, Bitcoin and other emerging technologies.</p>"



      [params.authors.Alex.social]
        twitter = "Alexandra933"
        linkedin = "alexandra-moxin"
        facebook = "alexandra.moxin"
        github = "lexi933"
        instagram = "lexi_933/?hl=en"
        pinterest = "lexi933"
        youtube = "results?search_query=alexandra+moxin"
        homepage = "https://medium.com/@Alexandra933"


    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
