baseurl = "https://advancetechmedia.org/"
languageCode = "en-US"
title = "Advance Tech Podcast"
theme = "castanet"
googleAnalytics = "UA-98351650-1"
disqusShortname = "advtechpodcast"
themesdir = "themes"


[permalinks]
	# page = "/:filename/"
	about = "/:filename/"
	episode = "/:filename/"


# The theme supports menus with up to one submenu per menu item
# The menu name must be "Main"
# The menus are sorted based upon their identifier

[[Menu.Main]]
    name = "Events"
    identifier = "events"
    url = "events"

[[Menu.Main]]
    name = "Guests"
    identifier = "guest"
    url = "guest"

[[Menu.Main]]
    name = "About"
    identifier = "about"
    url = "about"

 [[Menu.Main]]
   name = "Sponsor"
   identifier = "sponsor"
   url = "sponsor"

#[[Menu.Main]]
#    name = "Books"
#    identifier = "books"
#    url = "books"
#    parent = "resources"
#[[Menu.Main]]
#    name = "Podcasts"
#    identifier = "podcasts"
#    url = "books"
#    parent = "resources"

[params]
site_theme = "blue"
site_layout = "row"
enable_jumbo = "true"
truncate = "100"
about_logo = "/img/Advancetechmedia avatar.png"

copyright_notice = "Copyright 2017 - 2018 [Advance Tech Media](https://advancetechmedia.org)"
itunes_subscribe = "https://itunes.apple.com/ca/podcast/advance-tech-podcast/id1278222771"
android_subscribe = "http://www.subscribeonandroid.com/advancetechmedia.org/episode/index.xml"
google_play_subscribe = "https://play.google.com/music/listen?u=0#/ps/Ixpkgrijhidwwxqyz4qwfh4azhm"
#sticher_subscribe = "http://www.stitcher.com/podcast/arrested-devops-2/arrested-devops"
soundcloud_subscribe = "https://soundcloud.com/user-716837148"
#pocketcasts_subscribe = "http://pcasts.in/feed/feeds.soundcloud.com/users/soundcloud:users:716837148/sounds.rss"
#mailchimp_subscribe = "//arresteddevops.us3.list-manage.com/subscribe/post?u=5e4cbcac996bb9df25f970a89&amp;id=154fa76bcc"
#rss_subscribe = "http://feed.com/myfeed" #only set this if you don't want to use the built-in feed
description = "<p>Welcome to the Advance Tech Podcast bringing you news you won’t hear in the mainstream media. Hosted by Alexandra Moxin and Adam Dymitruk. We provide a spotlight for innovative and disruptive initiatives and interview guests defining the technology of tomorrow.</p><p>Advance Tech Media is dedicated to advancing research and supporting the responsible application of bleeding edge technology and practices that foster quality, equality and sustainability."
media_prefix = "http://advancetechmedia.org/"
  [params.feed]
    feed_copyright = "Copyright 2017 - 2018 Advance Tech Media" #do not use markdown in this field; it is used in the feed
    itunes_subtitle = "Bringing you the latest in technology, sustainability and open source news!" #no markdown or HTML
    itunes_author = "Alexandra Moxin" #no markdown or HTML
    itunes_summary = "The Advance Tech Podcast brings you the latest in bleeding edge technology and open source news you won’t hear in the mainstream media. Hosted by Alexandra Moxin and Adam Dymitruk. We aim to give you the unbiased truth and interview guests who are defining the technology of tomorrow." # Limited to 4000 characters or less, plain text, no HTML
    itunes_owner_name = "Advance Tech Media"
    itunes_owner_email = "alexandra.moxin@advancetechmedia.org" #contains the e-mail address that will be used to contact the owner of the Podcast for communication specifically about their Podcast on iTunes. It will not be publicly displayed on iTunes.
    itunes_image = "http://advancetechmedia.org/img/advancetechmediaavataritunes.png" #fqdn to the image art for your podcast
    itunes_top_category = "Technology"
    itunes_first_sub_category = "Tech News"
    itunes_second_sub_category = "Software How-To"
    itunes_third_sub_category = "Podcasting"

  [params.social]
    github = "advancetechmedia"
    #gitlab = "mattstratton"
    twitter = "AdvTechPodcast"
    linkedin = "/company/advance-tech-media/"
    #facebook_admin = "500557137"  # This needs to be a page admin to get domain insights
    facebook = "advancetechmedia"
    #twitter_domain = "arresteddevops.com" # This domain shows in twitter cards as "View on `twitter_domain`"
    #googleplus = "ArrestedDevOps"
    #pinterest = "nozzleio"
    instagram = "advance_tech_media"
    youtube = "channel/UCNnsKDIRB-HjNUeuvj5IW9w"


  [params.authors]
    [params.authors.Adam]
      name	= "Adam Dymitruk"
      thumbnail = "img/host/adam-2016-small-square.png"
      bio = "CEO and Founder of Adaptech Solutions, and co-host of the Advance Tech Podcast, Adam is a passionate technologist and has worked in the field for a few decades in numerous roles. He has contributed to the scaling approaches in CQRS and Event Sourcing by introducing PAXOS to the consistency strategy in 2008. In 2011-2012, he helped Microsoft's Patterns and Practices team introduce modern open-source tooling to the CQRS Journey book project. He has inspired organisations to excel in modern software development workflows, inspired a culture of learning and instilled a modern approach to software architecture."
      [params.authors.Adam.social]
        github = "adymitruk"
        twitter = "adymitruk"
        linkedin = "eventsourcing"
        facebook = "adymitruk"
        homepage = "https://www.adaptechsolutions.net/about"
        #pinterest = "mattstratton"
        #instagram = "instagram"
        youtube = "adaptech"
    [params.authors.Alex]
      name = "Alexandra Moxin"
      thumbnail = "img/host/Alex.jpg"
      bio = "Global Connector, Leader, Founder of Advance Tech Media and Host of the Advance Tech Podcast. Alexandra is dedicated to advancing research in and the responsible application of bleeding edge technology such as AI, neural and distributed networks, ML and deep learning, blockchain, cryptocurrency, VR/AR and the event based platforms that support these. Alexandra has over a decade of experience developing business and community and brings an understanding of how event based system implementations impact organisations. She is a strong proponent of open source communities."
      [params.authors.Alex.social]
        twitter = "Alexandra933"
        linkedin = "alexandra-moxin"
        facebook = "alexandra.moxin"
        github = "lexi933"
        instagram = "lexi_933/?hl=en"


    [params.links]
      [params.links.ado]
        name = "Arrested DevOps"
        url = "https://www.arresteddevops.com"
      [params.links.ffs]
        name = "Food Fight Show"
        url = "https://foodfightshow.org"
      [params.links.sdt]
        name = "Software Defined Talk"
        url = "https://cote.io/podcasts/sdt/"
